"""CLI to scaffold a new skill in a robot package.

Usage:
    python -m robot_agent.new_skill <robot_pkg> <skill_name> [<file>] [--template generic|detect]

Examples:
    # Default (generic) -- creates kcare_robot/skills/wave.py + registers 'wave'
    python -m robot_agent.new_skill kcare_robot wave

    # Detect template -- includes mock _fetch_data() + detector client call
    python -m robot_agent.new_skill kcare_robot find_apple --template detect

    # Group multiple skills in one file -- appends to skills/arm.py
    python -m robot_agent.new_skill kcare_robot rotate arm
    python -m robot_agent.new_skill kcare_robot rotate arm.py    # same thing

Behaviour:
  - Refuses if `<skill_name>` is already a key in <pkg>.configs.skills_config:SKILL_CONFIGS.
  - Refuses if `def <skill_name>(` already exists in the target file.
  - If the target file already exists, appends a new function (and adds the
    required imports once if missing).
  - Otherwise creates the file with a minimal module header.
  - Updates <pkg>/configs/skills_config.py by inserting one entry before the
    closing brace of the SKILL_CONFIGS dict. Falls back to printing the line
    to add manually if the regex can't find the dict.

After scaffolding, restart the agent (`make terminate && make run`) and
refresh the UI to pick up the new skill.
"""

from __future__ import annotations

import argparse
import ast
import importlib
import re
import sys
from pathlib import Path

IDENT_RE = re.compile(r'^[a-z_][a-z0-9_]*$')


# ── Templates ────────────────────────────────────────────────────────────────

# --- generic template ---------------------------------------------------------

# Function-only body — appended when target file already exists.
GENERIC_FUNCTION_TEMPLATE = '''

def {name}(node, **params) -> dict:
    """Skill `{name}`. TODO: replace this stub."""
    log_data({{'msg': f'{name} called with params={{params}}'}})
    return {{'isdone': True, 'msg': '{name} stub'}}
'''


# Full module — used when creating a new file. Includes the log_data import.
GENERIC_NEW_FILE_TEMPLATE = '''"""Skill(s): {name}. Generated by `make skill-generic` -- edit freely."""

from robot_agent.skills import log_data

{function}'''


# --- detect template ----------------------------------------------------------
#
# Mocks the recognition pattern: fetch an RGB/depth frame from a registered
# camera agent, send it to a detector client (TCP), then log the annotated
# image. The user edits the agent name + detector name to match their setup.

DETECT_FUNCTION_TEMPLATE = """

def _fetch_data_{name}(node):
    \"\"\"Mock image fetch. Replace 'head_rgb'/'head_depth' with the agent
    names you registered in the Connections panel.\"\"\"
    a = node.agents
    rgb         = a['head_rgb'].get()         if 'head_rgb'         in a else None
    depth       = a['head_depth'].get()       if 'head_depth'       in a else None
    cam_params  = a['head_cam_params'].get()  if 'head_cam_params'  in a else None
    if rgb is None:
        raise Exception(\"camera agent 'head_rgb' not registered — add it in the Connections panel\")
    return {{
        'rgb':        rgb.get('im')         if isinstance(rgb,        dict) else rgb,
        'depth':      depth.get('im')       if isinstance(depth,      dict) else depth,
        'cam_params': cam_params.get('cam_params') if isinstance(cam_params, dict) else cam_params,
    }}


def {name}(node, **params) -> dict:
    \"\"\"Skill `{name}` — mock detector flow.

    1. Fetch an image from the camera agent (see _fetch_data_{name}).
    2. Send the image + params to the detector client over TCP.
    3. Log the result and return it.

    Edit the agent name, detector key, and request payload to match your setup.
    \"\"\"
    log_data({{'msg': f'{name} called with params={{params}}'}})

    # 1. fetch image
    data = _fetch_data_{name}(node)

    # 2. call the detector client (TCP). Register a TCP client named 'detector'
    #    (or rename below) in the Connections panel.
    detector = current().dm.get_client('detector')
    if detector is None:
        raise Exception(\"TCP client 'detector' not registered — add it in the Connections panel\")

    # Edit the request shape to match your detector server's contract.
    request = {{
        'detector': 'mask2grasps',   # detector name on the server side
        'image':    data['rgb'],
        **params,
    }}
    result = detector.send(request)  # -> whatever your server returns (dict / ndarray)

    # 3. log the annotated image so it shows up in the UI Camera panel
    log_data({{'log_image': data['rgb']}})

    return {{'isdone': True, 'msg': f'{name} done', 'result': result}}
"""


# Module header used when the file is created from scratch with --template detect.
DETECT_NEW_FILE_TEMPLATE = '''"""Skill(s): {name}. Generated by `make skill-detect` -- edit freely.

This file follows the "detect" pattern:
  - _fetch_data_<skill> pulls a frame from a registered camera agent.
  - the skill body sends that frame to a TCP detector client and logs the result.
"""

from robot_agent.skills import log_data
from robot_agent.state import current

{function}'''


LOG_DATA_IMPORT = 'from robot_agent.skills import log_data'
CURRENT_IMPORT  = 'from robot_agent.state import current'


# --- external template --------------------------------------------------------
#
# Standalone HTTP service that owns its own rclpy.Node + MultiThreadedExecutor.
# robot_agent only stores a URL and forwards POST /skill/<name> here.
# Lives in <pkg>/template_skills/<skill>_external.py, NOT registered in
# skills_config (external skills are registered via the UI Skills panel).

EXTERNAL_NEW_FILE_TEMPLATE = '''"""External skill `{name}` -- standalone HTTP service. Generated by `make skill-external`.

Runs in its own process (own rclpy.init, own Node, own lifecycle). The robot
agent only stores a URL and forwards POST /skill/{name} here.

Start the server:
    uvicorn {pkg}.template_skills.{name}_external:app --host 0.0.0.0 --port {port}

Register it once so the agent forwards calls here -- either in the Skills panel
("+ add" -> External, url=http://localhost:{port}/{name}) or via curl:

    curl -X POST http://localhost:8001/skills \\
         -H 'Content-Type: application/json' \\
         -d '{{"name": "{name}",
              "type": "external",
              "url":  "http://localhost:{port}/{name}",
              "timeout": 15,
              "method": "POST"}}'

Then call it like any other skill:
    curl -X POST http://localhost:8001/skill/{name} \\
         -H 'Content-Type: application/json' -d '{{}}'

Pros: no robot_agent / pyconnect import, any language, any ROS_DOMAIN_ID,
      crash isolation, custom timeout/headers via SkillDef.
Cons: extra process, HTTP overhead (~ms), no streaming feedback.
"""

import threading
import time

import rclpy
from rclpy.executors import MultiThreadedExecutor
from rclpy.node import Node
from rosinterfaces.srv import SendStringData
from fastapi import FastAPI

from pyconnect.utils import dict2str, str2dict


class {class_name}Node(Node):
    """Owns its own rclpy.Client. Spun in a background thread.

    Edit the ROS service name + interface to match your robot.
    """

    def __init__(self):
        super().__init__('{name}_external_node')
        self.cli = self.create_client(SendStringData, '{name}')

    def call(self, payload: dict, timeout: float = 10.0) -> dict:
        if not self.cli.wait_for_service(timeout_sec=2.0):
            return {{'isdone': False, 'msg': "service {name!r} unavailable"}}
        req = SendStringData.Request()
        req.req = dict2str(payload)
        future = self.cli.call_async(req)
        t0 = time.time()
        while rclpy.ok() and not future.done():
            if time.time() - t0 > timeout:
                return {{'isdone': False, 'msg': f'timeout after {{timeout}}s'}}
            time.sleep(0.02)
        return str2dict(future.result().ret)


if not rclpy.ok():
    rclpy.init()
_node = {class_name}Node()
_executor = MultiThreadedExecutor(num_threads=2)
_executor.add_node(_node)
threading.Thread(target=_executor.spin, daemon=True).start()


app = FastAPI(title='{name}-external')


@app.post('/{name}')
def {name}(payload: dict):
    """External skill `{name}`. Edit the body to suit your robot."""
    return _node.call(payload)
'''


# Default port suggested in docs + summary banner. Override via uvicorn --port.
EXTERNAL_DEFAULT_PORT = 9000


TEMPLATES = {
    'generic': {
        'function':      GENERIC_FUNCTION_TEMPLATE,
        'new_file':      GENERIC_NEW_FILE_TEMPLATE,
        'extra_imports': (),
        'subdir':        'skills',
        'register':      True,
    },
    'detect': {
        'function':      DETECT_FUNCTION_TEMPLATE,
        'new_file':      DETECT_NEW_FILE_TEMPLATE,
        'extra_imports': (CURRENT_IMPORT,),
        'subdir':        'skills',
        'register':      True,
    },
    'external': {
        # external skills are one-file-per-skill (FastAPI app), so no function-
        # append template — only the full-file template is used.
        'function':      None,
        'new_file':      EXTERNAL_NEW_FILE_TEMPLATE,
        'extra_imports': (),
        'subdir':        'template_skills',
        'register':      False,
    },
}


# ── Helpers ──────────────────────────────────────────────────────────────────

def _err(msg: str) -> None:
    print(f'[new-skill] ERROR: {msg}', file=sys.stderr)


def _info(msg: str) -> None:
    print(f'[new-skill] {msg}')


def _locate_package(pkg: str) -> Path:
    """Return the on-disk directory of an installed Python package."""
    try:
        mod = importlib.import_module(pkg)
    except ImportError as e:
        _err(f"cannot import {pkg!r}: {e}")
        _err(f"  Hint: pip install -e <path-to-{pkg}>")
        sys.exit(2)
    if mod.__file__ is None:
        _err(f"{pkg!r} has no __file__ (namespace package?)")
        sys.exit(2)
    return Path(mod.__file__).parent


def _skill_already_registered(pkg: str, skill: str) -> bool:
    """True iff `skill` is a key in <pkg>.configs.skills_config:SKILL_CONFIGS."""
    try:
        cfg = importlib.import_module(f'{pkg}.configs.skills_config')
    except ImportError:
        return False
    return skill in getattr(cfg, 'SKILL_CONFIGS', {})


def _resolve_target_file(skills_dir: Path, skill: str, file_arg: str | None) -> Path:
    """Resolve the target file path inside skills_dir.

    - file_arg=None       -> <skill>.py
    - file_arg='arm'      -> arm.py
    - file_arg='arm.py'   -> arm.py
    Rejects anything containing path separators.
    """
    if file_arg is None or file_arg == '':
        file_name = f'{skill}.py'
    else:
        if '/' in file_arg or '\\' in file_arg:
            _err(f"FILE must be a filename (no subdirs); got {file_arg!r}")
            sys.exit(2)
        file_name = file_arg if file_arg.endswith('.py') else f'{file_arg}.py'
        stem = file_name[:-3]
        if not IDENT_RE.match(stem):
            _err(f"file stem {stem!r} is not a valid Python identifier")
            sys.exit(2)
    return skills_dir / file_name


def _function_exists_in(text: str, name: str) -> bool:
    """Check whether `def <name>(` appears at line start in `text`."""
    return re.search(rf'^def\s+{re.escape(name)}\s*\(', text, re.M) is not None


def _ensure_imports(text: str, imports: tuple[str, ...]) -> str:
    """Insert each required import once if missing.

    Placement (in order of preference):
      1. After the last existing top-level import.
      2. Else, after the module docstring (if any).
      3. Else, at the very top.

    Uses ast to avoid breaking docstrings or __future__ imports.
    """
    for imp in imports:
        if imp in text:
            continue
        lines = text.splitlines(keepends=True)
        try:
            tree = ast.parse(text)
        except SyntaxError:
            # Couldn't parse — fall back to dumb append at top.
            text = imp + '\n' + text
            continue

        last_import_lineno = 0
        for node in tree.body:
            if isinstance(node, (ast.Import, ast.ImportFrom)):
                last_import_lineno = max(last_import_lineno, node.end_lineno or node.lineno)

        if last_import_lineno > 0:
            insert_at = last_import_lineno
        else:
            if (tree.body
                    and isinstance(tree.body[0], ast.Expr)
                    and isinstance(tree.body[0].value, ast.Constant)
                    and isinstance(tree.body[0].value.value, str)):
                insert_at = tree.body[0].end_lineno or 1
            else:
                insert_at = 0

        insert_at = min(insert_at, len(lines))
        if insert_at > 0 and not lines[insert_at - 1].endswith('\n'):
            lines[insert_at - 1] = lines[insert_at - 1] + '\n'
        lines.insert(insert_at, imp + '\n')
        text = ''.join(lines)
    return text


def _append_to_existing_file(target: Path, skill: str, template_name: str) -> None:
    tpl = TEMPLATES[template_name]
    if tpl['function'] is None:
        # external template has no function-append form
        _err(f"template {template_name!r} does not support appending to an existing file")
        sys.exit(2)
    text = target.read_text()
    imports = (LOG_DATA_IMPORT,) + tpl['extra_imports']
    text = _ensure_imports(text, imports)
    if not text.endswith('\n'):
        text += '\n'
    text += tpl['function'].format(name=skill)
    target.write_text(text)


def _class_name_from_skill(skill: str) -> str:
    """`grip_external` -> `GripExternal`; `find` -> `Find`."""
    return ''.join(part.capitalize() for part in skill.split('_') if part) or 'Skill'


def _create_new_file(target: Path, skill: str, template_name: str, *, pkg: str) -> None:
    tpl = TEMPLATES[template_name]
    if template_name == 'external':
        body = tpl['new_file'].format(
            name=skill,
            pkg=pkg,
            class_name=_class_name_from_skill(skill),
            port=EXTERNAL_DEFAULT_PORT,
        )
    else:
        body = tpl['new_file'].format(
            name=skill,
            function=tpl['function'].format(name=skill).lstrip('\n'),
        )
    target.write_text(body)


def _register_in_skills_config(configs_file: Path, skill: str, file_stem: str) -> bool:
    """Insert a new entry inside SKILL_CONFIGS. Returns True on success.

    Strategy: locate ``SKILL_CONFIGS ... = {`` and walk braces forward to
    find the matching ``}``. Insert ``    '<skill>': (f'{_PKG}.<stem>', '<skill>'),``
    on a new line just before that ``}``, adding a trailing comma to the
    previous entry if it's missing.
    """
    if not configs_file.exists():
        _err(f"{configs_file} not found; cannot register")
        return False
    text = configs_file.read_text()
    new_entry_line = f"    '{skill}': (f'{{_PKG}}.{file_stem}', '{skill}'),"

    m = re.search(r'SKILL_CONFIGS\b[^=]*=\s*\{', text)
    if not m:
        _err(f"couldn't locate `SKILL_CONFIGS ... = {{` in {configs_file.name}")
        print(f'         add this line manually:\n         {new_entry_line}', file=sys.stderr)
        return False

    open_idx = m.end() - 1  # the '{'
    depth = 0
    close_idx: int | None = None
    for i, ch in enumerate(text[open_idx:], start=open_idx):
        if ch == '{':
            depth += 1
        elif ch == '}':
            depth -= 1
            if depth == 0:
                close_idx = i
                break
    if close_idx is None:
        _err(f"SKILL_CONFIGS dict in {configs_file.name} is not closed")
        print(f'         add this line manually:\n         {new_entry_line}', file=sys.stderr)
        return False

    before = text[:close_idx]
    after  = text[close_idx:]              # starts with '}'

    # Strip trailing whitespace, ensure trailing comma on previous entry.
    before_rstripped = before.rstrip()
    if before_rstripped.endswith('{'):
        # Empty dict: SKILL_CONFIGS = {  }
        updated = before_rstripped + '\n' + new_entry_line + '\n' + after.lstrip(' \t')
    else:
        if not before_rstripped.endswith(','):
            before_rstripped += ','
        updated = before_rstripped + '\n' + new_entry_line + '\n' + after.lstrip(' \t')

    configs_file.write_text(updated)
    return True


# ── Main ─────────────────────────────────────────────────────────────────────

def main() -> int:
    parser = argparse.ArgumentParser(
        prog='python -m robot_agent.new_skill',
        description='Scaffold a new skill in a robot package.',
    )
    parser.add_argument('pkg',   help='importable robot package, e.g. kcare_robot')
    parser.add_argument('skill', help='skill name (lowercase, identifier)')
    parser.add_argument('file',  nargs='?', default=None,
                        help='target filename (default: <skill>.py). .py extension optional.')
    parser.add_argument('--template', choices=sorted(TEMPLATES.keys()), default='generic',
                        help='skill body template (default: generic)')
    args = parser.parse_args()

    if not IDENT_RE.match(args.skill):
        _err(f"skill name {args.skill!r} is not a valid Python identifier "
             "(lowercase letters/digits/underscores, starting with letter or _)")
        return 2

    tpl = TEMPLATES[args.template]
    pkg_dir     = _locate_package(args.pkg)
    work_dir    = pkg_dir / tpl['subdir']
    configs_dir = pkg_dir / 'configs'
    configs_file = configs_dir / 'skills_config.py'

    if not work_dir.is_dir():
        _err(f"expected {tpl['subdir']!r} dir at {work_dir}")
        return 2
    if tpl['register'] and not configs_dir.is_dir():
        _err(f"expected configs dir at {configs_dir}")
        return 2

    # Check registry duplicate (only for templates that register).
    if tpl['register'] and _skill_already_registered(args.pkg, args.skill):
        _info(f"skill {args.skill!r} already registered in {configs_file.name} — nothing to do.")
        return 0

    # External skills are one-file-per-skill — FILE arg is ignored.
    if args.template == 'external':
        if args.file:
            _info(f"ignoring FILE={args.file!r} — external skills are always written to <skill>_external.py")
        target_file = work_dir / f'{args.skill}_external.py'
        if target_file.exists():
            _err(f"{target_file.relative_to(pkg_dir.parent)} already exists — refusing to overwrite")
            return 2
    else:
        target_file = _resolve_target_file(work_dir, args.skill, args.file)

    # Check function-name duplicate in target file (if file exists)
    created_path: Path | None = None
    appended_path: Path | None = None
    if target_file.exists():
        existing = target_file.read_text()
        if _function_exists_in(existing, args.skill):
            _info(f"function `def {args.skill}` already exists in {target_file.name} — nothing to do.")
            return 0
        _append_to_existing_file(target_file, args.skill, args.template)
        appended_path = target_file
    else:
        _create_new_file(target_file, args.skill, args.template, pkg=args.pkg)
        created_path = target_file

    registered = False
    if tpl['register']:
        file_stem = target_file.stem
        registered = _register_in_skills_config(configs_file, args.skill, file_stem)

    # ── Summary banner ─────────────────────────────────────────────────────
    print()
    print('─' * 64)
    print(f"  Skill {args.skill!r} scaffolded (template: {args.template})")
    print('─' * 64)
    if created_path:
        print(f"  ✓ Created     {created_path.relative_to(pkg_dir.parent)}")
    if appended_path:
        print(f"  ✓ Appended    def {args.skill}()  → {appended_path.relative_to(pkg_dir.parent)}")
    if tpl['register']:
        if registered:
            print(f"  ✓ Registered  {configs_file.relative_to(pkg_dir.parent)}")
        else:
            print(f"  ⚠ Could not auto-register in {configs_file.relative_to(pkg_dir.parent)} (see message above)")
    print()
    print("  Next steps:")
    if args.template == 'external':
        rel = target_file.relative_to(pkg_dir.parent).with_suffix('').as_posix().replace('/', '.')
        print(f"    1. Start the external server:")
        print(f"         uvicorn {rel}:app --host 0.0.0.0 --port {EXTERNAL_DEFAULT_PORT}")
        print(f"    2. Register it once -- either in the Skills panel UI")
        print(f"       (\"+ add\" -> External, url=http://localhost:{EXTERNAL_DEFAULT_PORT}/{args.skill})")
        print(f"       or via curl:")
        print(f"         curl -X POST http://localhost:8001/skills \\")
        print(f"              -H 'Content-Type: application/json' \\")
        print(f"              -d '{{\"name\":\"{args.skill}\",\"type\":\"external\","
              f"\"url\":\"http://localhost:{EXTERNAL_DEFAULT_PORT}/{args.skill}\","
              f"\"timeout\":15,\"method\":\"POST\"}}'")
        print(f"    3. Refresh the UI (or click ⟳ in the Skills panel)")
    else:
        print("    1. Restart the agent:  make terminate && make run")
        print("    2. Refresh the UI (or click ⟳ in the Skills panel) to pick up the new skill")
    print('─' * 64)
    return 0


if __name__ == '__main__':
    sys.exit(main())
